import { KnowledgeEntity } from '@/types/knowledge';

export const INITIAL_KNOWLEDGE_BASE: KnowledgeEntity[] = [
  {
    id: 'topic-nestjs',
    slug: 'nestjs',
    type: 'topic',
    title: 'NestJS Framework & Enterprise Architecture',
    description: 'A progressive Node.js framework for building efficient, reliable and scalable server-side applications.',
    summary: 'Comprehensive guide and graph of NestJS modules, decorators, dependency injection, and backend patterns.',
    category: 'Backend Development',
    tags: ['nestjs', 'nodejs', 'typescript', 'architecture'],
    difficulty: 'intermediate',
    createdAt: '2026-01-10T00:00:00.000Z',
    updatedAt: '2026-07-20T00:00:00.000Z',
    readingTimeMin: 12,
    officialDocs: ['https://docs.nestjs.com'],
    githubLinks: ['https://github.com/nestjs/nest'],
    references: [
      { title: 'NestJS Official Documentation', url: 'https://docs.nestjs.com', type: 'official-doc' }
    ],
    relatedTopics: ['typescript-senior'],
    relatedSkills: ['skill-validation-pipe', 'skill-exception-filter'],
    relatedProjects: ['project-banking-ledger'],
    relatedArchitectures: ['arch-backend-clean']
  },
  {
    id: 'skill-validation-pipe',
    slug: 'validation-pipe',
    type: 'skill',
    title: 'NestJS Validation Pipe & DTO Validation',
    description: 'Enforcing runtime payload validation using NestJS built-in ValidationPipe and class-validator.',
    summary: 'Learn how to automatically parse and sanitize incoming HTTP request bodies via Data Transfer Objects.',
    category: 'Backend Security & Clean Code',
    tags: ['nestjs', 'validation', 'dto', 'class-validator'],
    difficulty: 'intermediate',
    createdAt: '2026-02-01T00:00:00.000Z',
    updatedAt: '2026-07-15T00:00:00.000Z',
    readingTimeMin: 8,
    officialDocs: ['https://docs.nestjs.com/techniques/validation'],
    relatedTopics: ['nestjs'],
    relatedSkills: ['skill-exception-filter'],
    relatedMcps: ['mcp-class-validator-gen'],
    relatedArchitectures: ['arch-backend-clean']
  },
  {
    id: 'skill-exception-filter',
    slug: 'exception-filter',
    type: 'skill',
    title: 'Global Exception Filters & Error Handling',
    description: 'Catching and standardizing unhandled application exceptions across all HTTP and RPC entrypoints.',
    summary: 'Implement robust centralized error logging, error response formatting, and security masking in NestJS.',
    category: 'Backend Resilience',
    tags: ['nestjs', 'error-handling', 'filters', 'resilience'],
    difficulty: 'advanced',
    createdAt: '2026-02-10T00:00:00.000Z',
    updatedAt: '2026-07-18T00:00:00.000Z',
    readingTimeMin: 10,
    officialDocs: ['https://docs.nestjs.com/exception-filters'],
    relatedTopics: ['nestjs'],
    relatedSkills: ['skill-validation-pipe'],
    relatedAgents: ['agent-security-auditor'],
    relatedProjects: ['project-banking-ledger']
  },
  {
    id: 'mcp-class-validator-gen',
    slug: 'class-validator-mcp',
    type: 'mcp',
    title: 'Class Validator MCP Server',
    description: 'Model Context Protocol server for automatically generating and validating DTO schemas from database entities.',
    summary: 'Enables AI Agents to automatically verify incoming payload schemas and generate boilerplate class-validator decorators.',
    category: 'AI Tools & MCP',
    tags: ['mcp', 'class-validator', 'dto', 'ai-tool'],
    difficulty: 'intermediate',
    createdAt: '2026-03-05T00:00:00.000Z',
    updatedAt: '2026-07-22T00:00:00.000Z',
    readingTimeMin: 5,
    githubLinks: ['https://github.com/example/mcp-class-validator'],
    relatedSkills: ['skill-validation-pipe'],
    relatedAgents: ['agent-backend-architect'],
    relatedProjects: ['project-banking-ledger']
  },
  {
    id: 'agent-backend-architect',
    slug: 'backend-architect-agent',
    type: 'agent',
    title: 'Backend Architecture & Audit Agent',
    description: 'Autonomous AI agent specialized in reviewing backend codebases for security, validation, and clean architecture compliance.',
    summary: 'Evaluates controller endpoints, exception boundaries, and DTO validations automatically.',
    category: 'AI Agents',
    tags: ['agent', 'architecture', 'code-review', 'backend'],
    difficulty: 'advanced',
    createdAt: '2026-03-15T00:00:00.000Z',
    updatedAt: '2026-07-23T00:00:00.000Z',
    readingTimeMin: 7,
    relatedMcps: ['mcp-class-validator-gen', 'mcp-playwright-security'],
    relatedArchitectures: ['arch-backend-clean'],
    relatedProjects: ['project-banking-ledger']
  },
  {
    id: 'arch-backend-clean',
    slug: 'clean-backend-architecture',
    type: 'architecture',
    title: 'Clean Enterprise Backend Architecture',
    description: 'Decoupled, layer-based backend architecture pattern enforcing strict domain boundary separation.',
    summary: 'Combines Domain Driven Design, NestJS dependency injection, DTO validation pipelines, and standardized error responses.',
    category: 'Architecture',
    tags: ['architecture', 'ddd', 'clean-architecture', 'backend'],
    difficulty: 'advanced',
    createdAt: '2026-01-20T00:00:00.000Z',
    updatedAt: '2026-07-21T00:00:00.000Z',
    readingTimeMin: 15,
    relatedTopics: ['nestjs'],
    relatedProjects: ['project-banking-ledger'],
    relatedSkills: ['skill-validation-pipe', 'skill-exception-filter']
  },
  {
    id: 'project-banking-ledger',
    slug: 'banking-ledger-system',
    type: 'project',
    title: 'High-Throughput Banking Ledger System',
    description: 'Production-grade financial transaction ledger built with NestJS, Prisma, PostgreSQL, and strict DTO validation pipes.',
    summary: 'Real-world reference implementation demonstrating double-entry ledger security, idempotent transactions, and automated error filters.',
    category: 'Projects',
    tags: ['project', 'banking', 'ledger', 'nestjs', 'fintech'],
    difficulty: 'advanced',
    createdAt: '2026-04-01T00:00:00.000Z',
    updatedAt: '2026-07-24T00:00:00.000Z',
    readingTimeMin: 20,
    githubLinks: ['https://github.com/example/banking-ledger'],
    relatedTopics: ['nestjs'],
    relatedArchitectures: ['arch-backend-clean'],
    relatedSkills: ['skill-validation-pipe']
  },
  {
    id: 'topic-nextjs-senior',
    slug: 'nextjs-senior',
    type: 'topic',
    title: 'Next.js App Router & Server Components OS',
    description: 'Mastery of Next.js 16+ App Router, Server Actions, Dynamic Data Streaming, and ISR.',
    summary: 'Complete guide to building high-performance modern web platforms using React Server Components.',
    category: 'Frontend Development',
    tags: ['nextjs', 'react', 'typescript', 'app-router'],
    difficulty: 'advanced',
    createdAt: '2026-01-05T00:00:00.000Z',
    updatedAt: '2026-07-24T00:00:00.000Z',
    readingTimeMin: 15,
    officialDocs: ['https://nextjs.org/docs'],
    relatedSkills: ['skill-server-components'],
    relatedMcps: ['mcp-playwright-security'],
    relatedProjects: ['project-crisne-website']
  },
  {
    id: 'mcp-playwright-security',
    slug: 'playwright-security-mcp',
    type: 'mcp',
    title: 'Playwright E2E & Security Testing MCP',
    description: 'Model Context Protocol integration providing web testing, visual regression, and security audit tools for browser applications.',
    summary: 'Allows AI agents to execute automated browser interactions, verify DOM accessibility, and audit web application endpoints.',
    category: 'AI Tools & MCP',
    tags: ['mcp', 'playwright', 'security', 'e2e', 'testing'],
    difficulty: 'intermediate',
    createdAt: '2026-05-10T00:00:00.000Z',
    updatedAt: '2026-07-24T00:00:00.000Z',
    readingTimeMin: 6,
    githubLinks: ['https://github.com/example/mcp-playwright'],
    relatedAgents: ['agent-security-auditor'],
    relatedTopics: ['nextjs-senior']
  },
  {
    id: 'agent-security-auditor',
    slug: 'security-auditor-agent',
    type: 'agent',
    title: 'Frontend & API Security Auditor Agent',
    description: 'Automated agent that inspects HTTP headers, authentication boundaries, cross-site script risks, and API schemas.',
    summary: 'Uses Playwright MCP and REST API OpenAPI contracts to continuously test security posture.',
    category: 'AI Agents',
    tags: ['agent', 'security', 'auditor', 'mcp'],
    difficulty: 'advanced',
    createdAt: '2026-05-15T00:00:00.000Z',
    updatedAt: '2026-07-24T00:00:00.000Z',
    readingTimeMin: 9,
    relatedMcps: ['mcp-playwright-security'],
    relatedSkills: ['skill-exception-filter']
  }
];
